const data = [
  {
    business_status: 'OPERATIONAL',
    formatted_address: '500 N Azusa Ave, West Covina, CA 91791, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    id: 'c172092d8f2aadec15e22c499ca7185fbbc316cb',
    name: 'Mr Pollo',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJ8-Jh_zkow4ARxi5AF3dwL_8',
    plus_code: {
      compound_code: '33HV+R3 West Covina, California',
      global_code: '856433HV+R3',
    },
    price_level: 2,
    rating: 4.4,
    reference: 'ChIJ8-Jh_zkow4ARxi5AF3dwL_8',
    types: [
      'meal_delivery',
      'restaurant',
      'food',
      'point_of_interest',
      'establishment',
    ],
    user_ratings_total: 671,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '501 N Azusa Ave, West Covina, CA 91791, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    id: 'e40a19d7f3125a214b3e8c8b13814eb871fddb2d',
    name: 'NORMS Restaurant',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJkX03CToow4ARarq4jfEYjA0',
    plus_code: {
      compound_code: '33HR+QP West Covina, California',
      global_code: '856433HR+QP',
    },
    price_level: 1,
    rating: 4,
    reference: 'ChIJkX03CToow4ARarq4jfEYjA0',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 2832,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '540 N Azusa Ave, Covina, CA 91722, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    id: '8533f507c1c0ac69d5015f4228ca40b86a50f6f1',
    name: "Clearman's North Woods Inn of Covina",
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJl6_a-BUow4ARTO5WBNficTk',
    plus_code: {
      compound_code: '33QV+W5 Covina, California',
      global_code: '856433QV+W5',
    },
    price_level: 3,
    rating: 4.5,
    reference: 'ChIJl6_a-BUow4ARTO5WBNficTk',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 2905,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '381 N Azusa Ave, West Covina, CA 91791, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    id: 'faf26a6c3e8cf96464259e06c6d7a8dc03d674da',
    name: 'Rio Picanha Steakhouse',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJUw4LDWMpw4ARbVdeF6FUQNs',
    plus_code: {
      compound_code: '33GR+GP West Covina, California',
      global_code: '856433GR+GP',
    },
    rating: 4.6,
    reference: 'ChIJUw4LDWMpw4ARbVdeF6FUQNs',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 335,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '316 N Azusa Ave, Covina, CA 91722, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    id: '1298ee62b20c0eb58575e0067cd4fc39974895d7',
    name: "Sun's New Kitchen",
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJD-oaLjEow4ARIIrxcNbFZKk',
    plus_code: {
      compound_code: '33QV+6F Covina, California',
      global_code: '856433QV+6F',
    },
    rating: 4.4,
    reference: 'ChIJD-oaLjEow4ARIIrxcNbFZKk',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 75,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address:
      '450 N Azusa Ave D, West Covina, CA 91791, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    name: 'Pho Ha Linh',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJ0fwcqzAow4ARKLN_RZxL4bw',
    plus_code: {
      compound_code: '33HV+H3 West Covina, California',
      global_code: '856433HV+H3',
    },
    rating: 3.9,
    reference: 'ChIJ0fwcqzAow4ARKLN_RZxL4bw',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 60,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '523 N Azusa Ave, Covina, CA 91722, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    id: 'e30b138b22c7eef413751fab876be674ceabb933',
    name: 'Tijuana Restaurant',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJReedAxYow4ARa3dC-2TmZLo',
    plus_code: {
      compound_code: '33QR+QC Covina, California',
      global_code: '856433QR+QC',
    },
    price_level: 1,
    rating: 4.1,
    reference: 'ChIJReedAxYow4ARa3dC-2TmZLo',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 326,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address:
      '1118 W San Bernardino Rd, Covina, CA 91722, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    name: 'Mar Y Tierra Restaurant',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJf44W_Rcow4ARGhQ7xt_iGn0',
    plus_code: {
      compound_code: '33QP+9X Covina, California',
      global_code: '856433QP+9X',
    },
    price_level: 2,
    rating: 4.3,
    reference: 'ChIJf44W_Rcow4ARGhQ7xt_iGn0',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 374,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address:
      '500 N Azusa Ave #110, West Covina, CA 91791, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    id: '41b12139071f0111b48ec7a6d4c24c4080cab9b3',
    name: "Papa John's Pizza",
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJ8-Jh_zkow4AREd7b-iQNiOM',
    plus_code: {
      compound_code: '33HV+Q3 West Covina, California',
      global_code: '856433HV+Q3',
    },
    price_level: 1,
    rating: 4.1,
    reference: 'ChIJ8-Jh_zkow4AREd7b-iQNiOM',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 83,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '422 N Azusa Ave, Covina, CA 91722, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    id: 'bdd3df3c46d73609834cdc30fcbbf364e5824b7a',
    name: 'The Spot Teriyaki & Burgers',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJ509AIhYow4ARpEOaYOWGKpU',
    plus_code: {
      compound_code: '33QV+GF Covina, California',
      global_code: '856433QV+GF',
    },
    price_level: 1,
    rating: 4.6,
    reference: 'ChIJ509AIhYow4ARpEOaYOWGKpU',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 322,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '327 N Azusa Ave, West Covina, CA 91791, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    name: "Uncle Tim's Thai House",
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJ00yTNjEow4ARmr6-QJUqc7Q',
    plus_code: {
      compound_code: '33GR+8F West Covina, California',
      global_code: '856433GR+8F',
    },
    rating: 4.3,
    reference: 'ChIJ00yTNjEow4ARmr6-QJUqc7Q',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 171,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '645 N Azusa Ave, West Covina, CA 91791, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    name: "Denny's",
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJYc6VxTsow4ARdXQpETvsbbU',
    plus_code: {
      compound_code: '33JR+XP West Covina, California',
      global_code: '856433JR+XP',
    },
    price_level: 1,
    rating: 4.2,
    reference: 'ChIJYc6VxTsow4ARdXQpETvsbbU',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 1251,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address:
      '349 N Azusa Ave #101, West Covina, CA 91719, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    id: '0e27105b1f7940437317ffeb09fafa271895b5ce',
    name: 'Tasty Goody Chinese Fast Food',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJXfzJNjEow4AR58e6hN3iU5g',
    plus_code: {
      compound_code: '33GR+G6 West Covina, California',
      global_code: '856433GR+G6',
    },
    price_level: 1,
    rating: 4.3,
    reference: 'ChIJXfzJNjEow4AR58e6hN3iU5g',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 639,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '323 N Azusa Ave, West Covina, CA 91791, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    name: 'L&L Hawaiian Barbecue',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJI62SNjEow4ARklBTnv8WcM0',
    plus_code: {
      compound_code: '33GR+8M West Covina, California',
      global_code: '856433GR+8M',
    },
    price_level: 1,
    rating: 4.2,
    reference: 'ChIJI62SNjEow4ARklBTnv8WcM0',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 198,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '314 N Azusa Ave, West Covina, CA 91791, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    id: 'ca7fe6d20b6452de644e8c910b75292a1dbec4fe',
    name: 'Taqueria La Fogata',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJ24UKMzEow4ARJJFjujt35R8',
    plus_code: {
      compound_code: '33GV+C3 West Covina, California',
      global_code: '856433GV+C3',
    },
    rating: 3.9,
    reference: 'ChIJ24UKMzEow4ARJJFjujt35R8',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 306,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '519 N Azusa Ave, Covina, CA 91722, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    id: '093130781d9f8635f4d950826ea54f297bfa41ee',
    name: 'Sushi & Roll Japanese Cuisine',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJBWZ0IRYow4ARjhs86i6aEek',
    plus_code: {
      compound_code: '33QR+Q9 Covina, California',
      global_code: '856433QR+Q9',
    },
    price_level: 2,
    rating: 4.3,
    reference: 'ChIJBWZ0IRYow4ARjhs86i6aEek',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 122,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address:
      '1039 W San Bernardino Rd, Covina, CA 91722, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    name: 'Super Albert Fresh Mexican Food',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJofUp1hcow4ARVknXc15fxcs',
    plus_code: {
      compound_code: '33QQ+QJ Covina, California',
      global_code: '856433QQ+QJ',
    },
    price_level: 1,
    rating: 4.2,
    reference: 'ChIJofUp1hcow4ARVknXc15fxcs',
    types: [
      'meal_takeaway',
      'restaurant',
      'food',
      'point_of_interest',
      'establishment',
    ],
    user_ratings_total: 306,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '420 N Azusa Ave, Covina, CA 91722, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    id: 'a5fcf7379acae1af52dacd5273bdc3e52c04cc4a',
    name: 'Yoshinoya Covina',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJSa4d4j0ow4ARF1CLWnpROiY',
    plus_code: {
      compound_code: '33QV+F2 Covina, California',
      global_code: '856433QV+F2',
    },
    price_level: 1,
    rating: 4,
    reference: 'ChIJSa4d4j0ow4ARF1CLWnpROiY',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 572,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '621 N Azusa Ave, Covina, CA 91722, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    name: 'El Pollo Loco',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJEyG3fBYow4ARAAryF-btRdo',
    plus_code: {
      compound_code: '33RR+QQ Covina, California',
      global_code: '856433RR+QQ',
    },
    price_level: 1,
    rating: 4.3,
    reference: 'ChIJEyG3fBYow4ARAAryF-btRdo',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 414,
  },
  {
    business_status: 'OPERATIONAL',
    formatted_address: '402 N Azusa Ave, Covina, CA 91722, United States',
    geometry: { location: [Object], viewport: [Object] },
    icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    name: 'BMC Pho',
    opening_hours: { open_now: true },
    photos: [[Object]],
    place_id: 'ChIJcZVt4D0ow4ARvxbpDzXm5Is',
    plus_code: {
      compound_code: '33QV+92 Covina, California',
      global_code: '856433QV+92',
    },
    price_level: 1,
    rating: 4.2,
    reference: 'ChIJcZVt4D0ow4ARvxbpDzXm5Is',
    types: ['restaurant', 'food', 'point_of_interest', 'establishment'],
    user_ratings_total: 445,
  },
];
